# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-21 07:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='角色名称:')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='用户名称:')),
                ('password', models.CharField(max_length=32, verbose_name='密码:')),
                ('age', models.IntegerField(verbose_name='年龄:')),
                ('sex', models.CharField(max_length=32, verbose_name='性别:')),
                ('roles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Role', verbose_name='角色')),
            ],
        ),
    ]
